// glyphs.proto defines the Glyph struct in protobuf format.
//
// This is needed as a workaround to a Go compiler problem
// where a 13MB map literal causes the Go 1.11.5 compiler
// to use 12GB of virtual memory and die with the error:
//
// internal compiler error: bvbulkalloc too big:
// nbit=8072 count=7353122 nword=253 size=1860339866

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: glyphs.proto

package glyphs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Glyphs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Glyphs []*Glyph `protobuf:"bytes,1,rep,name=glyphs,proto3" json:"glyphs,omitempty"`
}

func (x *Glyphs) Reset() {
	*x = Glyphs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glyphs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Glyphs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Glyphs) ProtoMessage() {}

func (x *Glyphs) ProtoReflect() protoreflect.Message {
	mi := &file_glyphs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Glyphs.ProtoReflect.Descriptor instead.
func (*Glyphs) Descriptor() ([]byte, []int) {
	return file_glyphs_proto_rawDescGZIP(), []int{0}
}

func (x *Glyphs) GetGlyphs() []*Glyph {
	if x != nil {
		return x.Glyphs
	}
	return nil
}

type Glyph struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HorizAdvX float64     `protobuf:"fixed64,1,opt,name=horiz_adv_x,json=horizAdvX,proto3" json:"horiz_adv_x,omitempty"`
	Unicode   string      `protobuf:"bytes,2,opt,name=unicode,proto3" json:"unicode,omitempty"`
	GerberLP  string      `protobuf:"bytes,3,opt,name=gerber_l_p,json=gerberLP,proto3" json:"gerber_l_p,omitempty"`
	PathSteps []*PathStep `protobuf:"bytes,4,rep,name=path_steps,json=pathSteps,proto3" json:"path_steps,omitempty"`
	Mbb       *MBB        `protobuf:"bytes,5,opt,name=mbb,proto3" json:"mbb,omitempty"`
}

func (x *Glyph) Reset() {
	*x = Glyph{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glyphs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Glyph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Glyph) ProtoMessage() {}

func (x *Glyph) ProtoReflect() protoreflect.Message {
	mi := &file_glyphs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Glyph.ProtoReflect.Descriptor instead.
func (*Glyph) Descriptor() ([]byte, []int) {
	return file_glyphs_proto_rawDescGZIP(), []int{1}
}

func (x *Glyph) GetHorizAdvX() float64 {
	if x != nil {
		return x.HorizAdvX
	}
	return 0
}

func (x *Glyph) GetUnicode() string {
	if x != nil {
		return x.Unicode
	}
	return ""
}

func (x *Glyph) GetGerberLP() string {
	if x != nil {
		return x.GerberLP
	}
	return ""
}

func (x *Glyph) GetPathSteps() []*PathStep {
	if x != nil {
		return x.PathSteps
	}
	return nil
}

func (x *Glyph) GetMbb() *MBB {
	if x != nil {
		return x.Mbb
	}
	return nil
}

type PathStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C uint32    `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	P []float64 `protobuf:"fixed64,2,rep,packed,name=p,proto3" json:"p,omitempty"`
}

func (x *PathStep) Reset() {
	*x = PathStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glyphs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathStep) ProtoMessage() {}

func (x *PathStep) ProtoReflect() protoreflect.Message {
	mi := &file_glyphs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathStep.ProtoReflect.Descriptor instead.
func (*PathStep) Descriptor() ([]byte, []int) {
	return file_glyphs_proto_rawDescGZIP(), []int{2}
}

func (x *PathStep) GetC() uint32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *PathStep) GetP() []float64 {
	if x != nil {
		return x.P
	}
	return nil
}

type MBB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xmin float64 `protobuf:"fixed64,1,opt,name=xmin,proto3" json:"xmin,omitempty"`
	Ymin float64 `protobuf:"fixed64,2,opt,name=ymin,proto3" json:"ymin,omitempty"`
	Xmax float64 `protobuf:"fixed64,3,opt,name=xmax,proto3" json:"xmax,omitempty"`
	Ymax float64 `protobuf:"fixed64,4,opt,name=ymax,proto3" json:"ymax,omitempty"`
}

func (x *MBB) Reset() {
	*x = MBB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glyphs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MBB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MBB) ProtoMessage() {}

func (x *MBB) ProtoReflect() protoreflect.Message {
	mi := &file_glyphs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MBB.ProtoReflect.Descriptor instead.
func (*MBB) Descriptor() ([]byte, []int) {
	return file_glyphs_proto_rawDescGZIP(), []int{3}
}

func (x *MBB) GetXmin() float64 {
	if x != nil {
		return x.Xmin
	}
	return 0
}

func (x *MBB) GetYmin() float64 {
	if x != nil {
		return x.Ymin
	}
	return 0
}

func (x *MBB) GetXmax() float64 {
	if x != nil {
		return x.Xmax
	}
	return 0
}

func (x *MBB) GetYmax() float64 {
	if x != nil {
		return x.Ymax
	}
	return 0
}

var File_glyphs_proto protoreflect.FileDescriptor

var file_glyphs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x22, 0x2f, 0x0a, 0x06, 0x47, 0x6c, 0x79, 0x70, 0x68, 0x73,
	0x12, 0x25, 0x0a, 0x06, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x2e, 0x47, 0x6c, 0x79, 0x70, 0x68, 0x52,
	0x06, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x05, 0x47, 0x6c, 0x79, 0x70,
	0x68, 0x12, 0x1e, 0x0a, 0x0b, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x5f, 0x61, 0x64, 0x76, 0x5f, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x41, 0x64, 0x76,
	0x58, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x67,
	0x65, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x6c, 0x5f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x65, 0x72, 0x62, 0x65, 0x72, 0x4c, 0x50, 0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x61, 0x74,
	0x68, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x67, 0x6c, 0x79, 0x70, 0x68, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x53, 0x74, 0x65, 0x70, 0x52,
	0x09, 0x70, 0x61, 0x74, 0x68, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x6d, 0x62,
	0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x73,
	0x2e, 0x4d, 0x42, 0x42, 0x52, 0x03, 0x6d, 0x62, 0x62, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x61, 0x74,
	0x68, 0x53, 0x74, 0x65, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x01,
	0x70, 0x22, 0x55, 0x0a, 0x03, 0x4d, 0x42, 0x42, 0x12, 0x12, 0x0a, 0x04, 0x78, 0x6d, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x78, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x79, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x79, 0x6d, 0x69, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x78, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x78, 0x6d, 0x61, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x79, 0x6d, 0x61, 0x78, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6d, 0x6c, 0x65, 0x77, 0x69, 0x73, 0x2f, 0x67,
	0x6f, 0x2d, 0x66, 0x6f, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6c, 0x79, 0x70, 0x68,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_glyphs_proto_rawDescOnce sync.Once
	file_glyphs_proto_rawDescData = file_glyphs_proto_rawDesc
)

func file_glyphs_proto_rawDescGZIP() []byte {
	file_glyphs_proto_rawDescOnce.Do(func() {
		file_glyphs_proto_rawDescData = protoimpl.X.CompressGZIP(file_glyphs_proto_rawDescData)
	})
	return file_glyphs_proto_rawDescData
}

var file_glyphs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_glyphs_proto_goTypes = []interface{}{
	(*Glyphs)(nil),   // 0: glyphs.Glyphs
	(*Glyph)(nil),    // 1: glyphs.Glyph
	(*PathStep)(nil), // 2: glyphs.PathStep
	(*MBB)(nil),      // 3: glyphs.MBB
}
var file_glyphs_proto_depIdxs = []int32{
	1, // 0: glyphs.Glyphs.glyphs:type_name -> glyphs.Glyph
	2, // 1: glyphs.Glyph.path_steps:type_name -> glyphs.PathStep
	3, // 2: glyphs.Glyph.mbb:type_name -> glyphs.MBB
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_glyphs_proto_init() }
func file_glyphs_proto_init() {
	if File_glyphs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_glyphs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Glyphs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_glyphs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Glyph); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_glyphs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_glyphs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MBB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_glyphs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_glyphs_proto_goTypes,
		DependencyIndexes: file_glyphs_proto_depIdxs,
		MessageInfos:      file_glyphs_proto_msgTypes,
	}.Build()
	File_glyphs_proto = out.File
	file_glyphs_proto_rawDesc = nil
	file_glyphs_proto_goTypes = nil
	file_glyphs_proto_depIdxs = nil
}
