name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: check gofmt errors
      run: diff -u <(echo -n) <(gofmt -d -s .) || (echo "Please check go formatting!" && exit 1)

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...
